"""Render the Kubernetes manifests for the opt-in AKS compute profile from the workload list in
infra/main.bicep, so AKS runs the same fifteen workloads, commands and service names as Container
Apps. `--check` fails if the committed manifests in k8s/ are stale (CI). Never applied to a cluster.

Per workload: a ServiceAccount (Entra Workload ID), a Deployment (non-root, read-only root
filesystem, no privilege escalation, all capabilities dropped, RuntimeDefault seccomp, requests and
limits matching the Container App size), a ClusterIP Service on port 80 for HTTP workloads (so
`http://<name>` works as it does in Container Apps) and a PodDisruptionBudget. The namespace
enforces the `restricted` Pod Security Standard, and network policy is default deny for ingress and
egress with explicit allow rules."""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "k8s"
NS = "aiip"
IMAGE = "registry.example/aiip-platform:replace-me"  # set to <acr>.azurecr.io/aiip-platform@sha256:...
PLACEHOLDER_CLIENT_ID = "00000000-0000-0000-0000-000000000000"  # the workload's managed identity
PORT = 8080
PART_OF = {"app.kubernetes.io/part-of": "aiip"}
# the AKS application routing add-on (managed NGINX) runs its controller in this namespace
INGRESS_NS = "app-routing-system"
HEADER = "# Generated by scripts/render_k8s.py from infra/main.bicep; do not edit by hand.\n"


def workloads() -> list[dict]:
    """Parse the gateways, mcpServers, agents and workers arrays out of infra/main.bicep."""
    text = (ROOT / "infra" / "main.bicep").read_text()
    out = []
    for array in ("gateways", "mcpServers", "agents", "workers"):
        body = re.search(rf"^var {array} = \[\n(.*?)^\]", text, re.M | re.S).group(1)
        for line in body.strip().splitlines():
            name = re.search(r"name: '([\w-]+)'", line).group(1)
            reg = re.search(r"reg: '([\w-]+)'", line).group(1)
            command = re.findall(r"'([^']*)'", re.search(r"command: \[(.*?)\]", line).group(1))
            queue = re.search(r"queue: '([\w-]+)'", line)
            external = "external: true" in line
            kind = "worker" if array == "workers" else "http"
            out.append(
                {
                    "name": name,
                    "reg": reg,
                    "command": command,
                    "external": external,
                    "kind": kind,
                    "queue": queue.group(1) if queue else None,
                }
            )
    return out


def _labels(name: str) -> dict:
    return {"app.kubernetes.io/name": name, **PART_OF}


def _env(w: dict, http_names: list[str]) -> list[dict]:
    env = [
        {"name": "AIIP_MODE", "value": "azure"},
        {"name": "PORT", "value": str(PORT)},
        {"name": "HOST", "value": "0.0.0.0"},
        {"name": "AIIP_WORKLOAD_REGISTRATION", "value": w["reg"]},
    ]
    if w["queue"]:
        env.append({"name": "WORKER_QUEUE", "value": w["queue"]})
    env += [{"name": f"AIIP_{n.upper().replace('-', '_')}_URL", "value": f"http://{n}"} for n in http_names]
    return env


def workload_docs(w: dict, http_names: list[str]) -> list[dict]:
    name, http = w["name"], w["kind"] == "http"
    sa = {
        "apiVersion": "v1",
        "kind": "ServiceAccount",
        "metadata": {
            "name": name,
            "namespace": NS,
            "labels": _labels(name),
            "annotations": {"azure.workload.identity/client-id": PLACEHOLDER_CLIENT_ID},
        },
    }
    container = {
        "name": "main",
        "image": IMAGE,
        "imagePullPolicy": "IfNotPresent",
        "command": w["command"],
        "env": _env(w, http_names),
        "envFrom": [{"configMapRef": {"name": "aiip-azure"}}],
        "resources": {
            "requests": {"cpu": "250m", "memory": "512Mi"},
            "limits": {"cpu": "500m", "memory": "1Gi"},
        },
        "securityContext": {
            "allowPrivilegeEscalation": False,
            "readOnlyRootFilesystem": True,
            "runAsNonRoot": True,
            "capabilities": {"drop": ["ALL"]},
        },
        "volumeMounts": [{"name": "tmp", "mountPath": "/tmp"}],
    }
    if http:
        container["ports"] = [{"name": "http", "containerPort": PORT, "protocol": "TCP"}]
        probe = {"httpGet": {"path": "/healthz", "port": "http"}}
        container["readinessProbe"] = {**probe, "periodSeconds": 10}
        container["livenessProbe"] = {**probe, "periodSeconds": 30, "failureThreshold": 3}
    pod_labels = {**_labels(name), "azure.workload.identity/use": "true"}
    if w["external"]:
        pod_labels["aiip.example/edge"] = "true"
    deployment = {
        "apiVersion": "apps/v1",
        "kind": "Deployment",
        "metadata": {"name": name, "namespace": NS, "labels": _labels(name)},
        "spec": {
            "replicas": 2 if http else 1,
            "revisionHistoryLimit": 3,
            "selector": {"matchLabels": {"app.kubernetes.io/name": name}},
            "template": {
                "metadata": {"labels": pod_labels},
                "spec": {
                    "serviceAccountName": name,
                    # the Workload ID webhook mounts its own projected token; no API token needed
                    "automountServiceAccountToken": False,
                    "securityContext": {
                        "runAsNonRoot": True,
                        "runAsUser": 10001,
                        "runAsGroup": 10001,
                        "fsGroup": 10001,
                        "seccompProfile": {"type": "RuntimeDefault"},
                    },
                    "containers": [container],
                    "volumes": [{"name": "tmp", "emptyDir": {"sizeLimit": "64Mi"}}],
                    "topologySpreadConstraints": [
                        {
                            "maxSkew": 1,
                            "topologyKey": "kubernetes.io/hostname",
                            "whenUnsatisfiable": "ScheduleAnyway",
                            "labelSelector": {"matchLabels": {"app.kubernetes.io/name": name}},
                        }
                    ],
                },
            },
        },
    }
    docs = [sa, deployment]
    if http:
        docs.append(
            {
                "apiVersion": "v1",
                "kind": "Service",
                "metadata": {"name": name, "namespace": NS, "labels": _labels(name)},
                "spec": {
                    "type": "ClusterIP",
                    "selector": {"app.kubernetes.io/name": name},
                    "ports": [{"name": "http", "port": 80, "targetPort": "http", "protocol": "TCP"}],
                },
            }
        )
    pdb_spec = {"minAvailable": 1} if http else {"maxUnavailable": 1}
    docs.append(
        {
            "apiVersion": "policy/v1",
            "kind": "PodDisruptionBudget",
            "metadata": {"name": name, "namespace": NS, "labels": _labels(name)},
            "spec": {**pdb_spec, "selector": {"matchLabels": {"app.kubernetes.io/name": name}}},
        }
    )
    return docs


def namespace_docs() -> list[dict]:
    pss = {f"pod-security.kubernetes.io/{m}": "restricted" for m in ("enforce", "audit", "warn")}
    return [
        {"apiVersion": "v1", "kind": "Namespace", "metadata": {"name": NS, "labels": {**PART_OF, **pss}}},
        {
            "apiVersion": "v1",
            "kind": "ConfigMap",
            "metadata": {"name": "aiip-azure", "namespace": NS, "labels": dict(PART_OF)},
            # filled from the Terraform/Bicep outputs at deploy time; never deployed, so empty here
            "data": {
                "AZURE_TENANT_ID": "",
                "AIIP_KEYVAULT_NAME": "",
                "AIIP_SERVICEBUS_NAMESPACE": "",
                "AIIP_EVENTGRID_TOPIC_ENDPOINT": "",
                "APPLICATIONINSIGHTS_CONNECTION_STRING": "",
                "AIIP_MI_PRINCIPALS": "",
            },
        },
    ]


def network_policy_docs() -> list[dict]:
    def np(name: str, spec: dict) -> dict:
        meta = {"name": name, "namespace": NS, "labels": dict(PART_OF)}
        return {"apiVersion": "networking.k8s.io/v1", "kind": "NetworkPolicy", "metadata": meta, "spec": spec}

    same_ns = {"podSelector": {"matchLabels": PART_OF}}
    tcp = [{"protocol": "TCP", "port": PORT}]
    return [
        np("default-deny-all", {"podSelector": {}, "policyTypes": ["Ingress", "Egress"]}),
        np(
            "allow-dns-egress",
            {
                "podSelector": {},
                "policyTypes": ["Egress"],
                "egress": [
                    {
                        "to": [
                            {
                                "namespaceSelector": {
                                    "matchLabels": {"kubernetes.io/metadata.name": "kube-system"}
                                },
                                "podSelector": {"matchLabels": {"k8s-app": "kube-dns"}},
                            }
                        ],
                        "ports": [{"protocol": "UDP", "port": 53}, {"protocol": "TCP", "port": 53}],
                    }
                ],
            },
        ),
        np(
            "allow-platform-internal",
            {
                "podSelector": {"matchLabels": PART_OF},
                "policyTypes": ["Ingress", "Egress"],
                "ingress": [{"from": [same_ns], "ports": tcp}],
                "egress": [{"to": [same_ns], "ports": tcp}],
            },
        ),
        np(
            "allow-ingress-controller-to-edge",
            {
                "podSelector": {"matchLabels": {"aiip.example/edge": "true"}},
                "policyTypes": ["Ingress"],
                "ingress": [
                    {
                        "from": [
                            {
                                "namespaceSelector": {
                                    "matchLabels": {"kubernetes.io/metadata.name": INGRESS_NS}
                                }
                            }
                        ],
                        "ports": tcp,
                    }
                ],
            },
        ),
        # Azure PaaS (Entra ID, Key Vault, Service Bus over AMQP or HTTPS, Event Grid, Monitor) and
        # SaaS vendors. NetworkPolicy cannot filter by FQDN; pair it with Azure Firewall or private
        # endpoints to narrow the destinations.
        np(
            "allow-azure-egress",
            {
                "podSelector": {"matchLabels": PART_OF},
                "policyTypes": ["Egress"],
                "egress": [
                    {
                        "to": [{"ipBlock": {"cidr": "0.0.0.0/0", "except": ["169.254.169.254/32"]}}],
                        "ports": [{"protocol": "TCP", "port": 443}, {"protocol": "TCP", "port": 5671}],
                    }
                ],
            },
        ),
    ]


def dump(docs: list[dict]) -> str:
    return HEADER + "---\n".join(yaml.safe_dump(d, sort_keys=False, width=120) for d in docs)


def render() -> dict[str, str]:
    ws = workloads()
    http_names = [w["name"] for w in ws if w["kind"] == "http"]
    files = {
        "namespace.yaml": dump(namespace_docs()),
        "network-policies.yaml": dump(network_policy_docs()),
    }
    for w in ws:
        files[f"workloads/{w['name']}.yaml"] = dump(workload_docs(w, http_names))
    resources = sorted(files)
    files["kustomization.yaml"] = HEADER + yaml.safe_dump(
        {
            "apiVersion": "kustomize.config.k8s.io/v1beta1",
            "kind": "Kustomization",
            "resources": ["namespace.yaml", "network-policies.yaml"]
            + [r for r in resources if r.startswith("workloads/")],
        },
        sort_keys=False,
    )
    return files


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true", help="fail if k8s/ is stale")
    args = ap.parse_args()
    files = render()
    stale = []
    for rel, text in files.items():
        path = OUT / rel
        if args.check:
            if not path.exists() or path.read_text() != text:
                stale.append(rel)
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)
    if args.check:
        existing = {p.relative_to(OUT).as_posix() for p in OUT.rglob("*.yaml")}
        stale += sorted(existing - set(files))
        if stale:
            print("stale k8s manifests (run python scripts/render_k8s.py):", ", ".join(stale))
            return 1
        print(f"k8s manifests current ({len(files)} files)")
        return 0
    print(f"wrote {len(files)} files to k8s/")
    return 0


if __name__ == "__main__":
    sys.exit(main())
